// server/client-vue/pages/AddResource.vue
<template>
    <div v-if="form">
        <h2 class="font-thin text-3xl mb-8">
            {{ editing ? 'Edit' : 'New' }} {{ resource.name }}
        </h2>

        <div class="w-full mt-6 bg-white rounded-lg">
            <div
                class="w-full border-b flex items-center border-grey-light py-6 px-12"
                v-for="(field, index) in resource.fields"
                :key="index"
            >
                <label class="w-1/4 text-lg font-thin text-grey-dark">
                    {{ field.name }}
                </label>

                <div class="w-2/4 flex flex-col">
                    <input
                        :type="getType(field)"
                        :placeholder="field.name"
                        :ref="field.attribute"
                        :name="field.attribute"
                        :class="
                            classnames(FORM_CONTROL, 'w-full', {
                                'border-2 border-red focus:border-red': form.errors.has(
                                    field.attribute
                                )
                            })
                        "
                        v-model="form.fields[field.attribute]"
                        v-if="
                            ['Text', 'Password', 'Num', 'Date'].includes(
                                field.type
                            )
                        "
                    />
                    <textarea
                        cols="3"
                        rows="3"
                        :placeholder="field.name"
                        v-if="field.type === 'Textarea'"
                        :class="
                            classnames(FORM_CONTROL, 'w-full py-5 h-auto', {
                                'border-2 border-red focus:border-red': form.errors.has(
                                    field.attribute
                                )
                            })
                        "
                        v-model="form.fields[field.attribute]"
                    ></textarea>
                    <span
                        v-if="form.errors.has(field.attribute)"
                        class="text-xs text-red font-thin"
                    >
                        {{ form.errors.get(field.attribute) }}
                    </span>
                </div>
            </div>
        </div>

        <div class="p-8 flex justify-end bg-grey-lighter shadow">
            <button :class="`${PRIMARY_BUTTON} mr-6`">
                {{
                    editing
                        ? 'Update & Continue Editing'
                        : 'Create & Add another'
                }}
            </button>
            <button
                @click="editing ? update() : create()"
                :class="`${PRIMARY_BUTTON}`"
            >
                {{ `${editing ? 'Update' : 'Create'} ${resource.name}` }}
            </button>
        </div>
    </div>
</template>

<script>
import FlatPickr from 'flatpickr'
import format from 'date-fns/format'
import { GET_RESOURCE } from '@store/modules/resources'

export default {
    /**
     *
     * Define the data for this resource
     *
     * @return {Object}
     *
     */
    data: () => ({
        form: null,
        editing: false,
        loadingResouce: false
    }),

    /**
     *
     * Define form as soon as form is mounted.
     *
     * @return {null}
     *
     */
    mounted() {
        const fields = {}

        /**
         *
         * Define if this component is in editing mode
         *
         * @var {Boolean}
         *
         */
        this.editing = this.$route.name === 'updateResource'

        /**
         *
         * Loop through fields for this resource and set the attribute on form.
         */
        this.resource.fields.forEach(field => {
            fields[field.attribute] = ''
        })

        /**
         * Get date fields
         *
         * @type {Array}
         *
         */
        const dateFields = this.getDateFields()

        const dateFormat = field => `YYYY-MM-DD ${field.enableTime ? 'mm:ss' : ''}`

        if (this.editing) {
            this.loadingResouce = true

            this.$store
                .dispatch(GET_RESOURCE, {
                    slug: this.resource.slug,
                    primaryKey: this.$route.params.resource
                })
                .then(response => {
                    Object.keys(fields).forEach(field => {
                        fields[field] = response.data[field]
                    })

                    this.form = new Pangaso.Form(fields)

                    this.loadingResouce = false

                    setTimeout(() => {
                        dateFields.forEach(field => {
                            const flatPickrOptions = {
                                defaultDate:
                                    response.data[field.attribute] ||
                                    new Date(),
                                enableTime: field.enableTime
                            }

                            FlatPickr(this.$refs[field.attribute], flatPickrOptions)

                            this.form.fields[field.attribute] = format(flatPickrOptions.defaultDate, dateFormat(field))
                        })
                    }, 0)
                })
        } else {
            this.form = new Pangaso.Form(fields)

            setTimeout(() => {
                dateFields.forEach(field => {
                    FlatPickr(this.$refs[field.attribute], {
                        defaultDate: new Date(),
                        enableTime: field.enableTime
                    })

                    this.form.fields[field.attribute] = format(new Date(), dateFormat(field))
                })
            }, 0)
        }
    },

    methods: {
        /**
         * Get a valid input type for a field
         *
         * @return {string}
         *
         */
        getType(field) {
            switch (field.type) {
                case 'Num':
                    return 'number'
                default:
                    return field.type.toLowerCase()
            }
        },

        /**
         *
         * Submit form to create resource
         *
         * @return {null}
         *
         */
        create() {
            this.form.post({
                url: `/resources/${this.resource.slug}`,
                then: () => {
                    this.$router.push(`/resources/${this.resource.slug}`)
                }
            })
        },

        /**
         *
         * Update an existing resource
         *
         * @return {null}
         *
         */
        update() {
            this.form.put({
                url: `/resources/${this.resource.slug}/${
                    this.$route.params.resource
                }`,
                then: () => {
                    this.$router.push(`/resources/${this.resource.slug}`)
                }
            })
        },

        /**
         *
         * Initialize all date fields with flatpickr
         *
         * @return {void}
         *
         */
        getDateFields() {
            return this.resource.fields.filter(field => field.type === 'Date')
        }
    }
}
</script>

// client/tools/resources/js/pages/AddResource.tsx
import * as React from 'react'
import * as format from 'date-fns/format'
import { AxiosError, AxiosResponse } from 'axios'

interface AddResourceStateInterface {
    resource: any
    form: any
    errors: any
    editing: boolean
}

interface AddResourcePropsInterface {
    match: {
        params: {
            resource: string
            primaryKey: string
        }
    }
    history: {
        push(path: string): void
    }
}

class AddResource extends React.Component<
    AddResourcePropsInterface,
    AddResourceStateInterface
> {
    state: AddResourceStateInterface = {
        resource: this.getCurrentResource(),
        form: {},
        errors: {},
        editing: !!this.props.match.params.primaryKey
    }

    /**
     *
     * Set default values
     *
     * @return {void}
     *
     */
    componentDidMount() {
        if (this.state.editing) {
            return this.fetchEditingResource()
        }

        this.populateFields()
    }

    /**
     *
     * Populate fields
     *
     * @param {object} data
     *
     * @return {void}
     *
     */
    private populateFields = (data: any = {}) => {
        const form: any = {}

        this.getCreationFields().forEach((field: any) => {
            form[field.attribute] =
                field.type === 'Date'
                    ? format(
                          data[field.attribute] || new Date(),
                          this.getFormat(field)
                      )
                    : data[field.attribute] || ''
        })

        this.setState({
            form
        })
    }

    /**
     *
     * Get the current resource based on resource param
     *
     */
    private getCurrentResource(
        slug: string = this.props.match.params.resource
    ) {
        return (window as any).Pangaso.resources.find(
            (resource: any) => resource.slug === slug
        )
    }

    /**
     *
     * Fetch the resource to be edited
     *
     */
    private fetchEditingResource() {
        ;(window as any).Pangaso.request()
            .get(
                `/resources/${this.state.resource.slug}/${
                    this.props.match.params.primaryKey
                }`
            )

            /**
             *
             * Populate fields when resource is fetched from api
             *
             */
            .then(({ data }: AxiosResponse) => {
                this.populateFields(data)
            })

            /**
             *
             * If there are any errors fetching fields, simply
             * redirectback to this resource page
             *
             */
            .catch(() => {
                ;(window as any).Pangaso.error('Failed fetching resource.')

                this.props.history.push(
                    `/resources/${this.state.resource.slug}`
                )
            })
    }

    /**
     *
     * Post request to server to save resource
     *
     * @return {void}
     *
     */
    private postResource = (redirect: boolean = true) => {
        ;(window as any).Pangaso.request()
            .post(`resources/${this.state.resource.slug}`, this.state.form)
            .then(() => {
                ;(window as any).Pangaso.success(
                    `${this.state.resource.name} created !`
                )

                redirect &&
                    this.props.history.push(
                        `/resources/${this.state.resource.slug}`
                    )
            })
            .catch(({ response }: AxiosError) => {
                if (response.status === 422) {
                    this.setState({
                        errors: response.data
                    })
                }
            })
    }

    /**
     *
     * Patch request to server to update resource
     *
     * @return {void}
     *
     */
    private updateResource = (redirect: boolean = true) => {
        ;(window as any).Pangaso.request()
            .put(
                `resources/${this.state.resource.slug}/${
                    this.props.match.params.primaryKey
                }`,
                this.state.form
            )
            .then(() => {
                ;(window as any).Pangaso.success(
                    `${this.state.resource.name} updated !`
                )

                redirect &&
                    this.props.history.push(
                        `/resources/${this.state.resource.slug}`
                    )
            })
            .catch(({ response }: AxiosError) => {
                if (response.status === 422) {
                    this.setState({
                        errors: response.data
                    })
                }
            })
    }

    /**
     *
     * @return {void}
     *
     */
    handleChange = (event: any) => {
        /**
         *
         * Handle the date field case
         *
         */
        if (event.name && event.date) {
            return this.setState({
                form: {
                    ...this.state.form,
                    [event.name]: event.date
                },
                errors: {
                    ...this.state.errors,
                    [event.name]: null
                }
            })
        }

        this.setState({
            form: {
                ...this.state.form,
                [event.target.name]: event.target.value
            },
            errors: {
                ...this.state.errors,
                [event.target.name]: null
            }
        })
    }

    /**
     *
     * Get date format
     *
     * @param {Object} field
     *
     * @return {string}
     *
     */
    private getFormat = (field: any): string =>
        `YYYY-MM-DD${field.enableTime ? ' mm:ss' : ''}`

    /**
     *
     * Get the fields shown for creation
     *
     * @return {array}
     *
     */
    private getCreationFields = (): Array<any> =>
        this.state.resource.fields.filter(
            (field: any) => !field.hideOnCreationForm
        )

    /**
     *
     * Get the fields shown for update
     *
     * @return {array}
     *
     */
    privateGetUpdateFields = (): Array<any> =>
        this.state.resource.fields.filder(
            (field: any) => !field.hideOnUpdateForm
        )

    /**
     *
     * Get a field from the component registry
     */
    private getField = (component: string) =>
        (window as any).Pangaso.fields[component]

    /**
     *
     * Render add resource
     *
     */
    render() {
        const { editing, errors, form, resource } = this.state
        const Button = (window as any).Pangaso.components['component-button']

        return (
            <React.Fragment>
                <h1 className="font-thin text-3xl mb-2">
                    {`${editing ? 'Edit' : 'New'}`} {resource.name}
                </h1>

                <div className="w-full mt-6 bg-white rounded-lg">
                    {this.getCreationFields().map(
                        (field: any, index: number) => {
                            const Field = this.getField(field.component)

                            return Field ? (
                                <div
                                    key={index}
                                    className="w-full border-b flex items-center border-grey-light py-6 px-12"
                                >
                                    <label className="w-1/4 text-lg font-thin text-grey-dark">
                                        {field.name}
                                    </label>

                                    <div className="w-2/4 flex flex-col">
                                        <Field
                                            className="w-full"
                                            name={field.attribute}
                                            placeholder={field.name}
                                            handler={this.handleChange}
                                            value={form[field.attribute]}
                                            dateOptions={{
                                                enableTime: field.enableTime
                                            }}
                                            error={errors[field.attribute]}
                                        />
                                    </div>
                                </div>
                            ) : null
                        }
                    )}
                </div>

                <div className="p-8 flex justify-end bg-grey-lighter shadow">
                    <Button
                        handler={
                            editing
                                ? () => this.updateResource(false)
                                : () => this.postResource(false)
                        }
                        label={
                            editing
                                ? 'Updated & Continue editing'
                                : 'Create & Add another'
                        }
                        className="mr-6"
                    />
                    <Button
                        className="mr-6"
                        handler={
                            editing ? this.updateResource : this.postResource
                        }
                        label={`${editing ? 'Update' : 'Create'} ${
                            resource.name
                        }`}
                    />
                </div>
            </React.Fragment>
        )
    }
}

export default AddResource
